


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."costco_daily_avg" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "avg_reg_price" real,
    "avg_prm_price" real,
    "date" "date"
);


ALTER TABLE "public"."costco_daily_avg" OWNER TO "postgres";


COMMENT ON TABLE "public"."costco_daily_avg" IS 'Daily average for regular and premium gas at Costco''s in Southern California.';



ALTER TABLE "public"."costco_daily_avg" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."costco_daily_avg_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."costco_prm_gas_by_loc" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date" "date",
    "url" "text",
    "price" real,
    "location" "text"
);


ALTER TABLE "public"."costco_prm_gas_by_loc" OWNER TO "postgres";


COMMENT ON TABLE "public"."costco_prm_gas_by_loc" IS 'Daily values for Costco gas at specific locations in Southern California.';



ALTER TABLE "public"."costco_prm_gas_by_loc" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."costco_prm_gas_by_loc_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."costco_reg_gas_by_loc" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date" "date",
    "url" "text",
    "price" real,
    "location" "text"
);


ALTER TABLE "public"."costco_reg_gas_by_loc" OWNER TO "postgres";


COMMENT ON TABLE "public"."costco_reg_gas_by_loc" IS 'Daily values for Costco gas at specific locations in Southern California.';



ALTER TABLE "public"."costco_reg_gas_by_loc" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."costco_regular_gas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."test_costco_daily_avg" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "avg_reg_price" real,
    "avg_prm_price" real,
    "date" "date"
);


ALTER TABLE "public"."test_costco_daily_avg" OWNER TO "postgres";


COMMENT ON TABLE "public"."test_costco_daily_avg" IS 'This is a duplicate of costco_daily_avg';



ALTER TABLE "public"."test_costco_daily_avg" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test_costco_daily_avg_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."test_costco_prm_gas_by_loc" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date" "date",
    "url" "text",
    "price" real,
    "location" "text"
);


ALTER TABLE "public"."test_costco_prm_gas_by_loc" OWNER TO "postgres";


COMMENT ON TABLE "public"."test_costco_prm_gas_by_loc" IS 'This is a duplicate of costco_prm_gas_by_loc';



ALTER TABLE "public"."test_costco_prm_gas_by_loc" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test_costco_prm_gas_by_loc_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."test_costco_reg_gas_by_loc" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date" "date",
    "url" "text",
    "price" real,
    "location" "text"
);


ALTER TABLE "public"."test_costco_reg_gas_by_loc" OWNER TO "postgres";


COMMENT ON TABLE "public"."test_costco_reg_gas_by_loc" IS 'This is a duplicate of costco_reg_gas_by_loc';



ALTER TABLE "public"."test_costco_reg_gas_by_loc" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test_costco_reg_gas_by_loc_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."costco_daily_avg"
    ADD CONSTRAINT "costco_daily_avg_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."costco_prm_gas_by_loc"
    ADD CONSTRAINT "costco_prm_gas_by_loc_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."costco_reg_gas_by_loc"
    ADD CONSTRAINT "costco_regular_gas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test_costco_daily_avg"
    ADD CONSTRAINT "test_costco_daily_avg_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test_costco_prm_gas_by_loc"
    ADD CONSTRAINT "test_costco_prm_gas_by_loc_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test_costco_reg_gas_by_loc"
    ADD CONSTRAINT "test_costco_reg_gas_by_loc_pkey" PRIMARY KEY ("id");



ALTER TABLE "public"."costco_daily_avg" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."costco_prm_gas_by_loc" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."costco_reg_gas_by_loc" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test_costco_daily_avg" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test_costco_prm_gas_by_loc" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test_costco_reg_gas_by_loc" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."costco_daily_avg" TO "anon";
GRANT ALL ON TABLE "public"."costco_daily_avg" TO "authenticated";
GRANT ALL ON TABLE "public"."costco_daily_avg" TO "service_role";



GRANT ALL ON SEQUENCE "public"."costco_daily_avg_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."costco_daily_avg_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."costco_daily_avg_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."costco_prm_gas_by_loc" TO "anon";
GRANT ALL ON TABLE "public"."costco_prm_gas_by_loc" TO "authenticated";
GRANT ALL ON TABLE "public"."costco_prm_gas_by_loc" TO "service_role";



GRANT ALL ON SEQUENCE "public"."costco_prm_gas_by_loc_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."costco_prm_gas_by_loc_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."costco_prm_gas_by_loc_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."costco_reg_gas_by_loc" TO "anon";
GRANT ALL ON TABLE "public"."costco_reg_gas_by_loc" TO "authenticated";
GRANT ALL ON TABLE "public"."costco_reg_gas_by_loc" TO "service_role";



GRANT ALL ON SEQUENCE "public"."costco_regular_gas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."costco_regular_gas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."costco_regular_gas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test_costco_daily_avg" TO "anon";
GRANT ALL ON TABLE "public"."test_costco_daily_avg" TO "authenticated";
GRANT ALL ON TABLE "public"."test_costco_daily_avg" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test_costco_daily_avg_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test_costco_daily_avg_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test_costco_daily_avg_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test_costco_prm_gas_by_loc" TO "anon";
GRANT ALL ON TABLE "public"."test_costco_prm_gas_by_loc" TO "authenticated";
GRANT ALL ON TABLE "public"."test_costco_prm_gas_by_loc" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test_costco_prm_gas_by_loc_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test_costco_prm_gas_by_loc_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test_costco_prm_gas_by_loc_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test_costco_reg_gas_by_loc" TO "anon";
GRANT ALL ON TABLE "public"."test_costco_reg_gas_by_loc" TO "authenticated";
GRANT ALL ON TABLE "public"."test_costco_reg_gas_by_loc" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test_costco_reg_gas_by_loc_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test_costco_reg_gas_by_loc_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test_costco_reg_gas_by_loc_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


